name: Auto Update Proxies

permissions: write-all

on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - main

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Proxy Script
      run: |
        cd Files
        python app.py
        python warp.py
        python sort.py

    - name: Pull Latest Changes from Remote
      run: |
        git pull origin main --rebase || echo "No changes to pull"

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Updated proxy files" || echo "No changes to commit"
        git push origin main

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
