name: Auto Update Proxies

on:
  schedule:
    - cron: "*/30 * * * *" 

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Proxy Script
      run: |
        python proxies.py

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git pull origin main --rebase || echo "No changes to pull"
        git add .
        git commit -m "Update proxy files" || echo "No changes to commit"
        git push origin HEAD:main
